import type { CropProfile } from '@/types/crop';

export const INITIAL_CROPS: CropProfile[] = [
  // ==================== CÂY TRỒNG CHUYÊN CANH: DƯA LƯỚI CÔNG NGHỆ CAO ====================
  {
    id: 'dua-luoi',
    name: 'Dưa Lưới',
    scientificName: 'Cucumis melo',
    category: 'fruit',
    icon: '🍈',
    totalDays: 75,
    difficulty: 'medium',
    vietnamSeason: 'Quanh năm nhà màng',
    description: 'Chuyên canh dưa lưới nhà màng công nghệ cao.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Cây con',
        daysRange: 'Ngày 1 - 12',
        durationDays: 12,
        temperature: { min: 22, max: 32, optimalMin: 24, optimalMax: 28 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 65, max: 80, optimalMin: 70, optimalMax: 75 },
        light: { min: 8000, max: 28000, optimalMin: 12000, optimalMax: 22000 },
        vpd: { min: 0.5, max: 0.9, optimalMin: 0.6, optimalMax: 0.8 },
        advisoryNote: 'Giữ ẩm 70-75%, che nắng gắt trưa.',
      },
      {
        stageId: 'flowering',
        name: 'Tuyển trái',
        daysRange: 'Ngày 13 - 35',
        durationDays: 23,
        temperature: { min: 24, max: 34, optimalMin: 26, optimalMax: 30 },
        airHumidity: { min: 60, max: 75, optimalMin: 65, optimalMax: 70 },
        soilMoisture: { min: 60, max: 75, optimalMin: 65, optimalMax: 72 },
        light: { min: 20000, max: 60000, optimalMin: 30000, optimalMax: 48000 },
        vpd: { min: 0.85, max: 1.35, optimalMin: 0.95, optimalMax: 1.2 },
        advisoryNote: 'Thụ phấn 7h-9h30, chọn 1 trái nách 10-12.',
      },
      {
        stageId: 'fruiting',
        name: 'Lên lưới & Brix',
        daysRange: 'Ngày 36 - 65',
        durationDays: 30,
        temperature: { min: 24, max: 35, optimalMin: 27, optimalMax: 31 },
        airHumidity: { min: 55, max: 70, optimalMin: 60, optimalMax: 65 },
        soilMoisture: { min: 55, max: 70, optimalMin: 60, optimalMax: 65 },
        light: { min: 22000, max: 65000, optimalMin: 32000, optimalMax: 50000 },
        vpd: { min: 1.0, max: 1.5, optimalMin: 1.1, optimalMax: 1.35 },
        advisoryNote: 'Tưới đều để lưới rạn đẹp, chống nứt vỏ.',
      },
      {
        stageId: 'harvest',
        name: 'Thu hoạch',
        daysRange: 'Ngày 66 - 75',
        durationDays: 10,
        temperature: { min: 22, max: 32, optimalMin: 25, optimalMax: 29 },
        airHumidity: { min: 50, max: 65, optimalMin: 55, optimalMax: 62 },
        soilMoisture: { min: 40, max: 55, optimalMin: 45, optimalMax: 52 },
        light: { min: 18000, max: 55000, optimalMin: 25000, optimalMax: 42000 },
        vpd: { min: 1.1, max: 1.6, optimalMin: 1.2, optimalMax: 1.45 },
        advisoryNote: 'Siết nước 7 ngày cuối để Brix ≥ 14%.',
      },
    ],
  },
];
