import type { CropProfile } from '@/types/crop';

export const INITIAL_CROPS: CropProfile[] = [
  // ==================== CÂY TRỒNG CHUYÊN CANH: DƯA LƯỚI CÔNG NGHỆ CAO ====================
  {
    id: 'dua-luoi',
    name: 'Dưa lưới ruột cam Kim Cô Nương',
    scientificName: 'Cucumis melo',
    category: 'fruit',
    icon: '🍈',
    totalDays: 75,
    difficulty: 'hard',
    vietnamSeason: 'Xuân - Hè khô ráo nhiều nắng',
    description: 'Đặc sản nhà màng công nghệ cao, yêu cầu kiểm soát độ ẩm và VPD cực kỳ nghiêm ngặt.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Cây con vườn ươm',
        daysRange: 'Ngày 1 - 12',
        durationDays: 12,
        temperature: { min: 22, max: 32, optimalMin: 24, optimalMax: 28 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 65, max: 80, optimalMin: 70, optimalMax: 75 },
        light: { min: 8000, max: 28000, optimalMin: 12000, optimalMax: 22000 },
        vpd: { min: 0.5, max: 0.9, optimalMin: 0.6, optimalMax: 0.8 },
        advisoryNote: 'Thụ phấn nhân tạo tốt nhất từ 7h - 9h30 sáng.',
      },
      {
        stageId: 'flowering',
        name: 'Thụ phấn & Tuyển trái',
        daysRange: 'Ngày 13 - 35',
        durationDays: 23,
        temperature: { min: 24, max: 34, optimalMin: 26, optimalMax: 30 },
        airHumidity: { min: 60, max: 75, optimalMin: 65, optimalMax: 70 },
        soilMoisture: { min: 60, max: 75, optimalMin: 65, optimalMax: 72 },
        light: { min: 20000, max: 60000, optimalMin: 30000, optimalMax: 48000 },
        vpd: { min: 0.85, max: 1.35, optimalMin: 0.95, optimalMax: 1.2 },
        advisoryNote: 'Chỉ giữ lại 1 trái chuẩn nhất ở nách lá thứ 10-12, tỉa hết trái phụ.',
      },
      {
        stageId: 'fruiting',
        name: 'Lên vân lưới & Tích lũy đường Brix',
        daysRange: 'Ngày 36 - 65',
        durationDays: 30,
        temperature: { min: 24, max: 35, optimalMin: 27, optimalMax: 31 },
        airHumidity: { min: 55, max: 70, optimalMin: 60, optimalMax: 65 },
        soilMoisture: { min: 55, max: 70, optimalMin: 60, optimalMax: 65 },
        light: { min: 22000, max: 65000, optimalMin: 32000, optimalMax: 50000 },
        vpd: { min: 1.0, max: 1.5, optimalMin: 1.1, optimalMax: 1.35 },
        advisoryNote: 'Điều tiết nước chuẩn để lưới rạn đều, tránh nứt toác vỏ.',
      },
      {
        stageId: 'harvest',
        name: 'Cắt nước & Thu hoạch',
        daysRange: 'Ngày 66 - 75',
        durationDays: 10,
        temperature: { min: 22, max: 32, optimalMin: 25, optimalMax: 29 },
        airHumidity: { min: 50, max: 65, optimalMin: 55, optimalMax: 62 },
        soilMoisture: { min: 40, max: 55, optimalMin: 45, optimalMax: 52 },
        light: { min: 18000, max: 55000, optimalMin: 25000, optimalMax: 42000 },
        vpd: { min: 1.1, max: 1.6, optimalMin: 1.2, optimalMax: 1.45 },
        advisoryNote: 'Giảm 50% lượng nước tưới trong 7 ngày cuối để tăng độ ngọt Brix lên 14-16%.',
      },
    ],
  },
  // ==================== 1. RAU ĂN LÁ (LEAFY) ====================
  {
    id: 'cai-ngot',
    name: 'Cải ngọt cao sản',
    scientificName: 'Brassica integrifolia',
    category: 'leafy',
    icon: '🥬',
    totalDays: 32,
    difficulty: 'easy',
    vietnamSeason: 'Quanh năm (Phát triển tốt nhất Thu - Đông)',
    description: 'Giống rau ăn lá phổ biến nhất tại Việt Nam, lớn nhanh, ưa ẩm mát và ánh sáng vừa đủ.',
    waterDemand: 'high',
    stages: [
      {
        stageId: 'seedling',
        name: 'Cây con & Bén rễ',
        daysRange: 'Ngày 1 - 7',
        durationDays: 7,
        temperature: { min: 20, max: 28, optimalMin: 22, optimalMax: 26 },
        airHumidity: { min: 70, max: 90, optimalMin: 75, optimalMax: 85 },
        soilMoisture: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        light: { min: 4000, max: 15000, optimalMin: 6000, optimalMax: 12000 },
        vpd: { min: 0.4, max: 0.8, optimalMin: 0.5, optimalMax: 0.75 },
        advisoryNote: 'Giữ ẩm bề mặt giá thể, che chắn ánh nắng gắt buổi trưa để bảo vệ mầm non.',
      },
      {
        stageId: 'vegetative',
        name: 'Phát triển thân lá',
        daysRange: 'Ngày 8 - 22',
        durationDays: 15,
        temperature: { min: 18, max: 30, optimalMin: 22, optimalMax: 27 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 60, max: 80, optimalMin: 65, optimalMax: 75 },
        light: { min: 8000, max: 35000, optimalMin: 12000, optimalMax: 25000 },
        vpd: { min: 0.7, max: 1.2, optimalMin: 0.8, optimalMax: 1.1 },
        advisoryNote: 'Giai đoạn tăng sinh khối nhanh, duy trì tưới đều đặn và kiểm soát bọ nhảy cắn lá.',
      },
      {
        stageId: 'harvest',
        name: 'Thu hoạch',
        daysRange: 'Ngày 23 - 32',
        durationDays: 10,
        temperature: { min: 18, max: 30, optimalMin: 20, optimalMax: 26 },
        airHumidity: { min: 60, max: 80, optimalMin: 65, optimalMax: 75 },
        soilMoisture: { min: 55, max: 70, optimalMin: 60, optimalMax: 68 },
        light: { min: 8000, max: 30000, optimalMin: 10000, optimalMax: 22000 },
        vpd: { min: 0.8, max: 1.3, optimalMin: 0.85, optimalMax: 1.15 },
        advisoryNote: 'Giảm nhẹ lượng nước tưới trước thu hoạch 2 ngày để rau giòn ngọt và để được lâu.',
      },
    ],
  },
  {
    id: 'cai-be-xanh',
    name: 'Cải bẹ xanh (Cải cay)',
    scientificName: 'Brassica juncea',
    category: 'leafy',
    icon: '🥗',
    totalDays: 35,
    difficulty: 'easy',
    vietnamSeason: 'Quanh năm, thích hợp mùa lạnh miền Bắc',
    description: 'Vị hơi cay nồng đặc trưng, giàu vitamin A, C, kháng sâu bệnh tốt hơn cải ngọt.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Ươm mầm & Cây con',
        daysRange: 'Ngày 1 - 8',
        durationDays: 8,
        temperature: { min: 18, max: 28, optimalMin: 20, optimalMax: 25 },
        airHumidity: { min: 70, max: 90, optimalMin: 75, optimalMax: 85 },
        soilMoisture: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        light: { min: 5000, max: 18000, optimalMin: 8000, optimalMax: 15000 },
        vpd: { min: 0.4, max: 0.8, optimalMin: 0.5, optimalMax: 0.75 },
        advisoryNote: 'Độ ẩm 75-80% kích thích rễ tơ phát triển khỏe mạnh.',
      },
      {
        stageId: 'vegetative',
        name: 'Mở rộng tán lá',
        daysRange: 'Ngày 9 - 25',
        durationDays: 17,
        temperature: { min: 18, max: 32, optimalMin: 22, optimalMax: 28 },
        airHumidity: { min: 60, max: 80, optimalMin: 65, optimalMax: 75 },
        soilMoisture: { min: 60, max: 75, optimalMin: 65, optimalMax: 70 },
        light: { min: 10000, max: 40000, optimalMin: 15000, optimalMax: 30000 },
        vpd: { min: 0.8, max: 1.3, optimalMin: 0.85, optimalMax: 1.15 },
        advisoryNote: 'Cần nhiều ánh sáng để bẹ lá dày và cuống giòn.',
      },
      {
        stageId: 'harvest',
        name: 'Thương phẩm & Thu hoạch',
        daysRange: 'Ngày 26 - 35',
        durationDays: 10,
        temperature: { min: 18, max: 30, optimalMin: 20, optimalMax: 26 },
        airHumidity: { min: 55, max: 75, optimalMin: 60, optimalMax: 70 },
        soilMoisture: { min: 50, max: 70, optimalMin: 55, optimalMax: 65 },
        light: { min: 8000, max: 30000, optimalMin: 12000, optimalMax: 22000 },
        vpd: { min: 0.8, max: 1.4, optimalMin: 0.9, optimalMax: 1.2 },
        advisoryNote: 'Thu hoạch vào sáng sớm khi sương vừa ráo để tránh dập lá.',
      },
    ],
  },
  {
    id: 'xa-lach-xoan',
    name: 'Xà lách xoăn Frisee / Romaine',
    scientificName: 'Lactuca sativa',
    category: 'leafy',
    icon: '🌱',
    totalDays: 45,
    difficulty: 'medium',
    vietnamSeason: 'Thu - Đông - Xuân (Tránh nắng gắt mùa hè)',
    description: 'Cây ưa thời tiết mát mẻ (18-24°C), nhạy cảm với nhiệt độ cao dễ bị trổ ngồng và đắng.',
    waterDemand: 'high',
    stages: [
      {
        stageId: 'seedling',
        name: 'Mầm tơ & Cây con',
        daysRange: 'Ngày 1 - 10',
        durationDays: 10,
        temperature: { min: 16, max: 24, optimalMin: 18, optimalMax: 22 },
        airHumidity: { min: 70, max: 85, optimalMin: 72, optimalMax: 80 },
        soilMoisture: { min: 65, max: 80, optimalMin: 70, optimalMax: 75 },
        light: { min: 4000, max: 16000, optimalMin: 6000, optimalMax: 12000 },
        vpd: { min: 0.4, max: 0.8, optimalMin: 0.5, optimalMax: 0.7 },
        advisoryNote: 'Nhiệt độ trên 28°C sẽ ức chế nảy mầm và làm mầm kéo dài yếu ớt.',
      },
      {
        stageId: 'vegetative',
        name: 'Cuộn búp & Xoăn lá',
        daysRange: 'Ngày 11 - 35',
        durationDays: 25,
        temperature: { min: 16, max: 25, optimalMin: 18, optimalMax: 23 },
        airHumidity: { min: 60, max: 75, optimalMin: 65, optimalMax: 70 },
        soilMoisture: { min: 60, max: 75, optimalMin: 65, optimalMax: 72 },
        light: { min: 10000, max: 30000, optimalMin: 15000, optimalMax: 24000 },
        vpd: { min: 0.7, max: 1.1, optimalMin: 0.8, optimalMax: 1.0 },
        advisoryNote: 'Duy trì VPD quanh 0.8-1.0 kPa để phòng ngừa bệnh cháy mép lá (Tipburn).',
      },
      {
        stageId: 'harvest',
        name: 'Đạt độ búp & Thu hoạch',
        daysRange: 'Ngày 36 - 45',
        durationDays: 10,
        temperature: { min: 15, max: 24, optimalMin: 18, optimalMax: 22 },
        airHumidity: { min: 55, max: 70, optimalMin: 60, optimalMax: 68 },
        soilMoisture: { min: 55, max: 70, optimalMin: 60, optimalMax: 65 },
        light: { min: 8000, max: 25000, optimalMin: 12000, optimalMax: 20000 },
        vpd: { min: 0.8, max: 1.2, optimalMin: 0.85, optimalMax: 1.1 },
        advisoryNote: 'Thu hoạch trước khi thân nhú ngồng hoa để vị ngọt giòn thanh khiết.',
      },
    ],
  },
  {
    id: 'rau-muong',
    name: 'Rau muống cạn lá liễu',
    scientificName: 'Ipomoea aquatica',
    category: 'leafy',
    icon: '🌿',
    totalDays: 26,
    difficulty: 'easy',
    vietnamSeason: 'Mùa hè, nhiệt đới nóng ẩm quanh năm',
    description: 'Tăng trưởng siêu tốc trong khí hậu nhiệt đới nắng ấm, chịu ngập và hút dinh dưỡng khỏe.',
    waterDemand: 'high',
    stages: [
      {
        stageId: 'seedling',
        name: 'Nảy mầm & Bén rễ',
        daysRange: 'Ngày 1 - 6',
        durationDays: 6,
        temperature: { min: 24, max: 35, optimalMin: 26, optimalMax: 32 },
        airHumidity: { min: 75, max: 95, optimalMin: 80, optimalMax: 90 },
        soilMoisture: { min: 70, max: 90, optimalMin: 75, optimalMax: 85 },
        light: { min: 6000, max: 25000, optimalMin: 10000, optimalMax: 20000 },
        vpd: { min: 0.4, max: 0.9, optimalMin: 0.5, optimalMax: 0.8 },
        advisoryNote: 'Cần đất ấm và độ ẩm cao để đánh thức hạt giống.',
      },
      {
        stageId: 'vegetative',
        name: 'Vươn ngọn & Đẻ nhánh',
        daysRange: 'Ngày 7 - 20',
        durationDays: 14,
        temperature: { min: 25, max: 36, optimalMin: 28, optimalMax: 33 },
        airHumidity: { min: 70, max: 90, optimalMin: 75, optimalMax: 85 },
        soilMoisture: { min: 70, max: 88, optimalMin: 75, optimalMax: 82 },
        light: { min: 15000, max: 60000, optimalMin: 25000, optimalMax: 45000 },
        vpd: { min: 0.8, max: 1.4, optimalMin: 0.9, optimalMax: 1.25 },
        advisoryNote: 'Cực kỳ ưa nắng, nắng càng to rau phát triển càng mập mạp và xanh non.',
      },
      {
        stageId: 'harvest',
        name: 'Thu hái đợt 1 & Tái sinh',
        daysRange: 'Ngày 21 - 26',
        durationDays: 6,
        temperature: { min: 24, max: 35, optimalMin: 26, optimalMax: 32 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 65, max: 80, optimalMin: 70, optimalMax: 78 },
        light: { min: 12000, max: 50000, optimalMin: 20000, optimalMax: 40000 },
        vpd: { min: 0.8, max: 1.4, optimalMin: 0.9, optimalMax: 1.2 },
        advisoryNote: 'Cắt cách gốc 3cm để các chồi nách bật đợt lứa mới sau 12 ngày.',
      },
    ],
  },
  {
    id: 'cai-kale',
    name: 'Cải xoăn Kale khủng long',
    scientificName: 'Brassica oleracea var. sabellica',
    category: 'leafy',
    icon: '🥬',
    totalDays: 70,
    difficulty: 'medium',
    vietnamSeason: 'Thu - Đông, Đà Lạt và vùng cao quanh năm',
    description: 'Siêu thực phẩm giàu khoáng chất, chịu lạnh tốt, lá xoăn dày, thu hoạch tỉa lá kéo dài.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Cây con vườn ươm',
        daysRange: 'Ngày 1 - 15',
        durationDays: 15,
        temperature: { min: 16, max: 26, optimalMin: 18, optimalMax: 23 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 60, max: 80, optimalMin: 65, optimalMax: 75 },
        light: { min: 5000, max: 20000, optimalMin: 8000, optimalMax: 16000 },
        vpd: { min: 0.5, max: 0.9, optimalMin: 0.6, optimalMax: 0.8 },
        advisoryNote: 'Cây con dễ bị thối cổ rễ nếu úng ngập, giữ đất tơi xốp thoát nước.',
      },
      {
        stageId: 'vegetative',
        name: 'Phát triển tán gân lá',
        daysRange: 'Ngày 16 - 50',
        durationDays: 35,
        temperature: { min: 15, max: 28, optimalMin: 18, optimalMax: 24 },
        airHumidity: { min: 60, max: 80, optimalMin: 65, optimalMax: 75 },
        soilMoisture: { min: 55, max: 75, optimalMin: 60, optimalMax: 70 },
        light: { min: 15000, max: 50000, optimalMin: 20000, optimalMax: 35000 },
        vpd: { min: 0.8, max: 1.3, optimalMin: 0.85, optimalMax: 1.15 },
        advisoryNote: 'Cần bổ sung kali và canxi để phiến lá dày, chống chọi sâu tơ.',
      },
      {
        stageId: 'harvest',
        name: 'Tỉa lá định kỳ liên tục',
        daysRange: 'Ngày 51 - 70',
        durationDays: 20,
        temperature: { min: 14, max: 28, optimalMin: 16, optimalMax: 22 },
        airHumidity: { min: 55, max: 75, optimalMin: 60, optimalMax: 70 },
        soilMoisture: { min: 55, max: 70, optimalMin: 60, optimalMax: 68 },
        light: { min: 12000, max: 45000, optimalMin: 18000, optimalMax: 32000 },
        vpd: { min: 0.8, max: 1.4, optimalMin: 0.9, optimalMax: 1.2 },
        advisoryNote: 'Thu hoạch lá già dưới gốc trước, chừa lại 6-8 lá non trên ngọn để cây tiếp tục lớn.',
      },
    ],
  },
  {
    id: 'mong-toi',
    name: 'Rau mồng tơi Nhật / Tím',
    scientificName: 'Basella alba',
    category: 'leafy',
    icon: '🍃',
    totalDays: 40,
    difficulty: 'easy',
    vietnamSeason: 'Xuân hè và mùa mưa nhiệt đới',
    description: 'Thân mọng nước, nhớt nhẹ nhuận tràng, chịu nắng nóng và ẩm cực tốt, ít sâu bệnh.',
    waterDemand: 'high',
    stages: [
      {
        stageId: 'seedling',
        name: 'Nảy mầm & Bén rễ',
        daysRange: 'Ngày 1 - 10',
        durationDays: 10,
        temperature: { min: 22, max: 34, optimalMin: 25, optimalMax: 30 },
        airHumidity: { min: 70, max: 90, optimalMin: 75, optimalMax: 85 },
        soilMoisture: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        light: { min: 6000, max: 25000, optimalMin: 10000, optimalMax: 20000 },
        vpd: { min: 0.5, max: 0.9, optimalMin: 0.6, optimalMax: 0.8 },
        advisoryNote: 'Hạt vỏ dày nên ngâm ủ ấm trước khi gieo.',
      },
      {
        stageId: 'vegetative',
        name: 'Leo giàn & Mập đọt',
        daysRange: 'Ngày 11 - 30',
        durationDays: 20,
        temperature: { min: 24, max: 36, optimalMin: 27, optimalMax: 32 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 65, max: 80, optimalMin: 70, optimalMax: 78 },
        light: { min: 15000, max: 55000, optimalMin: 22000, optimalMax: 40000 },
        vpd: { min: 0.8, max: 1.4, optimalMin: 0.9, optimalMax: 1.2 },
        advisoryNote: 'Bấm ngọn khi dây dài 20cm để kích thích đẻ nhiều nhánh nách.',
      },
      {
        stageId: 'harvest',
        name: 'Hái ngọn & Tỉa lá',
        daysRange: 'Ngày 31 - 40',
        durationDays: 10,
        temperature: { min: 22, max: 35, optimalMin: 25, optimalMax: 30 },
        airHumidity: { min: 60, max: 80, optimalMin: 65, optimalMax: 75 },
        soilMoisture: { min: 60, max: 75, optimalMin: 65, optimalMax: 72 },
        light: { min: 10000, max: 45000, optimalMin: 18000, optimalMax: 35000 },
        vpd: { min: 0.8, max: 1.4, optimalMin: 0.9, optimalMax: 1.2 },
        advisoryNote: 'Thu hái ngọn non dài 10-15cm vào buổi sáng để rau giòn mọng nước.',
      },
    ],
  },

  // ==================== 2. CÂY ĂN QUẢ (FRUIT) ====================
  {
    id: 'ca-chua-bi',
    name: 'Cà chua bi Cherry F1',
    scientificName: 'Solanum lycopersicum var. cerasiforme',
    category: 'fruit',
    icon: '🍅',
    totalDays: 85,
    difficulty: 'medium',
    vietnamSeason: 'Thu - Đông - Xuân (Đà Lạt quanh năm)',
    description: 'Trái nhỏ ngọt, giàu lycopene, năng suất cao nhưng mẫn cảm với úng rễ và nấm mốc lá.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Cây con & Bén rễ',
        daysRange: 'Ngày 1 - 15',
        durationDays: 15,
        temperature: { min: 18, max: 28, optimalMin: 21, optimalMax: 25 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 60, max: 75, optimalMin: 65, optimalMax: 70 },
        light: { min: 6000, max: 22000, optimalMin: 10000, optimalMax: 18000 },
        vpd: { min: 0.5, max: 0.9, optimalMin: 0.6, optimalMax: 0.8 },
        advisoryNote: 'Bảo vệ cây con khỏi bọ trĩ truyền virus xoăn ngọn.',
      },
      {
        stageId: 'vegetative',
        name: 'Tăng trưởng thân & Cành nách',
        daysRange: 'Ngày 16 - 40',
        durationDays: 25,
        temperature: { min: 18, max: 30, optimalMin: 22, optimalMax: 27 },
        airHumidity: { min: 60, max: 80, optimalMin: 65, optimalMax: 75 },
        soilMoisture: { min: 55, max: 75, optimalMin: 60, optimalMax: 70 },
        light: { min: 15000, max: 50000, optimalMin: 22000, optimalMax: 38000 },
        vpd: { min: 0.8, max: 1.3, optimalMin: 0.85, optimalMax: 1.15 },
        advisoryNote: 'Tỉa bỏ chồi nách phụ, cắm cọc giữ thân thẳng và thông thoáng gốc.',
      },
      {
        stageId: 'flowering',
        name: 'Ra hoa & Đậu trái non',
        daysRange: 'Ngày 41 - 60',
        durationDays: 20,
        temperature: { min: 18, max: 28, optimalMin: 20, optimalMax: 25 },
        airHumidity: { min: 55, max: 75, optimalMin: 60, optimalMax: 70 },
        soilMoisture: { min: 50, max: 68, optimalMin: 55, optimalMax: 65 },
        light: { min: 20000, max: 60000, optimalMin: 28000, optimalMax: 45000 },
        vpd: { min: 0.9, max: 1.4, optimalMin: 1.0, optimalMax: 1.25 },
        advisoryNote: 'Nhiệt độ trên 32°C hoặc độ ẩm >85% sẽ làm phấn hoa bết dính, giảm đậu trái.',
      },
      {
        stageId: 'fruiting_harvest',
        name: 'Đổi màu chín & Thu hoạch',
        daysRange: 'Ngày 61 - 85',
        durationDays: 25,
        temperature: { min: 18, max: 30, optimalMin: 21, optimalMax: 26 },
        airHumidity: { min: 50, max: 70, optimalMin: 55, optimalMax: 65 },
        soilMoisture: { min: 45, max: 65, optimalMin: 50, optimalMax: 60 },
        light: { min: 18000, max: 55000, optimalMin: 25000, optimalMax: 40000 },
        vpd: { min: 1.0, max: 1.5, optimalMin: 1.1, optimalMax: 1.35 },
        advisoryNote: 'Hạn chế tưới đẫm đột ngột trong giai đoạn chín để tránh nứt vỏ trái.',
      },
    ],
  },
  {
    id: 'dua-leo-baby',
    name: 'Dưa leo baby Hà Lan F1',
    scientificName: 'Cucumis sativus',
    category: 'fruit',
    icon: '🥒',
    totalDays: 50,
    difficulty: 'easy',
    vietnamSeason: 'Quanh năm nhiệt đới, tốt nhất Xuân - Hè',
    description: 'Sinh trưởng khỏe, hoa cái đơn tính tự đậu trái, vỏ mỏng không gai, năng suất cao.',
    waterDemand: 'high',
    stages: [
      {
        stageId: 'seedling',
        name: 'Cây con 3 lá thật',
        daysRange: 'Ngày 1 - 10',
        durationDays: 10,
        temperature: { min: 20, max: 30, optimalMin: 23, optimalMax: 27 },
        airHumidity: { min: 70, max: 88, optimalMin: 75, optimalMax: 82 },
        soilMoisture: { min: 65, max: 80, optimalMin: 70, optimalMax: 76 },
        light: { min: 8000, max: 25000, optimalMin: 12000, optimalMax: 20000 },
        vpd: { min: 0.5, max: 0.9, optimalMin: 0.6, optimalMax: 0.8 },
        advisoryNote: 'Cây con dưa leo bộ rễ yếu, tránh lay gốc và tránh tưới nước quá lạnh.',
      },
      {
        stageId: 'vegetative',
        name: 'Bò giàn & Phát triển tua cuốn',
        daysRange: 'Ngày 11 - 25',
        durationDays: 15,
        temperature: { min: 22, max: 32, optimalMin: 25, optimalMax: 29 },
        airHumidity: { min: 65, max: 80, optimalMin: 70, optimalMax: 75 },
        soilMoisture: { min: 65, max: 82, optimalMin: 70, optimalMax: 78 },
        light: { min: 18000, max: 55000, optimalMin: 25000, optimalMax: 42000 },
        vpd: { min: 0.8, max: 1.3, optimalMin: 0.85, optimalMax: 1.15 },
        advisoryNote: 'Quấn ngọn theo dây giàn, duy trì tưới đều để cuống không bị đắng.',
      },
      {
        stageId: 'harvest',
        name: 'Ra quả rộ & Thu hoạch hàng ngày',
        daysRange: 'Ngày 26 - 50',
        durationDays: 25,
        temperature: { min: 20, max: 32, optimalMin: 24, optimalMax: 28 },
        airHumidity: { min: 60, max: 78, optimalMin: 65, optimalMax: 72 },
        soilMoisture: { min: 60, max: 80, optimalMin: 68, optimalMax: 75 },
        light: { min: 18000, max: 55000, optimalMin: 24000, optimalMax: 40000 },
        vpd: { min: 0.9, max: 1.4, optimalMin: 0.95, optimalMax: 1.25 },
        advisoryNote: 'Thu trái kích thước 10-12cm mỗi 1-2 ngày để kích thích cây nuôi lứa trái tiếp theo.',
      },
    ],
  },
  {
    id: 'dau-tay',
    name: 'Dâu tây Hana / New Zealand',
    scientificName: 'Fragaria × ananassa',
    category: 'fruit',
    icon: '🍓',
    totalDays: 90,
    difficulty: 'hard',
    vietnamSeason: 'Xứ lạnh: Đà Lạt, Mộc Châu hoặc phòng lạnh công nghệ cao',
    description: 'Cực kỳ nhạy cảm với nhiệt độ cao và nấm bệnh phấn trắng, thích hợp 16-22°C.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Cây ngó bén rễ chậu',
        daysRange: 'Ngày 1 - 20',
        durationDays: 20,
        temperature: { min: 14, max: 24, optimalMin: 17, optimalMax: 21 },
        airHumidity: { min: 65, max: 80, optimalMin: 70, optimalMax: 76 },
        soilMoisture: { min: 60, max: 75, optimalMin: 65, optimalMax: 70 },
        light: { min: 8000, max: 25000, optimalMin: 12000, optimalMax: 20000 },
        vpd: { min: 0.5, max: 0.85, optimalMin: 0.6, optimalMax: 0.75 },
        advisoryNote: 'Giữ ẩm ngó dâu, tránh chôn sâu ngập điểm sinh trưởng trung tâm.',
      },
      {
        stageId: 'vegetative',
        name: 'Đâm hoa & Vươn ngồng quả',
        daysRange: 'Ngày 21 - 50',
        durationDays: 30,
        temperature: { min: 15, max: 25, optimalMin: 18, optimalMax: 22 },
        airHumidity: { min: 60, max: 75, optimalMin: 65, optimalMax: 70 },
        soilMoisture: { min: 55, max: 70, optimalMin: 60, optimalMax: 66 },
        light: { min: 15000, max: 40000, optimalMin: 20000, optimalMax: 32000 },
        vpd: { min: 0.75, max: 1.2, optimalMin: 0.85, optimalMax: 1.05 },
        advisoryNote: 'Lót rơm hoặc màng nylon cách ly quả với đất để ngăn thối nhũn.',
      },
      {
        stageId: 'harvest',
        name: 'Chín đỏ & Thu hoạch',
        daysRange: 'Ngày 51 - 90',
        durationDays: 40,
        temperature: { min: 14, max: 23, optimalMin: 16, optimalMax: 20 },
        airHumidity: { min: 55, max: 70, optimalMin: 58, optimalMax: 65 },
        soilMoisture: { min: 50, max: 65, optimalMin: 55, optimalMax: 60 },
        light: { min: 14000, max: 38000, optimalMin: 18000, optimalMax: 28000 },
        vpd: { min: 0.8, max: 1.25, optimalMin: 0.9, optimalMax: 1.15 },
        advisoryNote: 'Hái dâu lúc còn tai xanh 1 chút hoặc chín đỏ 90% khi sương tan.',
      },
    ],
  },
  {
    id: 'ot-chuong',
    name: 'Ớt chuông ngọt Đà Lạt',
    scientificName: 'Capsicum annuum',
    category: 'fruit',
    icon: '🫑',
    totalDays: 95,
    difficulty: 'medium',
    vietnamSeason: 'Mát mẻ Thu Đông, Tây Nguyên quanh năm',
    description: 'Thân thảo mọc đứng, giòn ngọt, giàu dinh dưỡng, mẫn cảm với úng rễ cục bộ.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Cây con vườn ươm',
        daysRange: 'Ngày 1 - 25',
        durationDays: 25,
        temperature: { min: 18, max: 28, optimalMin: 20, optimalMax: 25 },
        airHumidity: { min: 65, max: 80, optimalMin: 70, optimalMax: 75 },
        soilMoisture: { min: 60, max: 75, optimalMin: 65, optimalMax: 70 },
        light: { min: 8000, max: 25000, optimalMin: 12000, optimalMax: 20000 },
        vpd: { min: 0.5, max: 0.9, optimalMin: 0.6, optimalMax: 0.8 },
        advisoryNote: 'Đảm bảo khay ươm thoát nước tốt, ngừa lở cổ rễ.',
      },
      {
        stageId: 'flowering',
        name: 'Phân cành chữ Y & Đơm bông',
        daysRange: 'Ngày 26 - 60',
        durationDays: 35,
        temperature: { min: 18, max: 28, optimalMin: 21, optimalMax: 26 },
        airHumidity: { min: 60, max: 75, optimalMin: 65, optimalMax: 70 },
        soilMoisture: { min: 55, max: 70, optimalMin: 60, optimalMax: 65 },
        light: { min: 18000, max: 50000, optimalMin: 25000, optimalMax: 40000 },
        vpd: { min: 0.8, max: 1.3, optimalMin: 0.85, optimalMax: 1.15 },
        advisoryNote: 'Bấm bỏ hoa chét đầu tiên ở ngã ba cành để cây tập trung nuôi tán khỏe.',
      },
      {
        stageId: 'harvest',
        name: 'Quả lớn đẫy & Thu hoạch',
        daysRange: 'Ngày 61 - 95',
        durationDays: 35,
        temperature: { min: 18, max: 27, optimalMin: 20, optimalMax: 24 },
        airHumidity: { min: 55, max: 70, optimalMin: 60, optimalMax: 66 },
        soilMoisture: { min: 55, max: 68, optimalMin: 58, optimalMax: 64 },
        light: { min: 16000, max: 48000, optimalMin: 22000, optimalMax: 36000 },
        vpd: { min: 0.85, max: 1.35, optimalMin: 0.95, optimalMax: 1.2 },
        advisoryNote: 'Thu khi quả bóng căng, chuyển màu đỏ/vàng trên 80% bề mặt.',
      },
    ],
  },

  // ==================== 3. RAU GIA VỊ (HERB) ====================
  {
    id: 'hanh-la',
    name: 'Hành lá gốc trắng',
    scientificName: 'Allium fistulosum',
    category: 'herb',
    icon: '🌱',
    totalDays: 45,
    difficulty: 'easy',
    vietnamSeason: 'Quanh năm, thích hợp nhiều chân đất',
    description: 'Cây gia vị không thể thiếu trong bữa ăn Việt, rễ chùm nông rất sợ úng nước.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Bén rễ tép giống',
        daysRange: 'Ngày 1 - 10',
        durationDays: 10,
        temperature: { min: 18, max: 30, optimalMin: 22, optimalMax: 26 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 60, max: 75, optimalMin: 65, optimalMax: 70 },
        light: { min: 6000, max: 25000, optimalMin: 10000, optimalMax: 18000 },
        vpd: { min: 0.5, max: 0.9, optimalMin: 0.6, optimalMax: 0.8 },
        advisoryNote: 'Tưới giữ ẩm gốc nhẹ nhàng, tránh vòi nước mạnh xói bật gốc.',
      },
      {
        stageId: 'vegetative',
        name: 'Đẻ nhánh & Dày ống lá',
        daysRange: 'Ngày 11 - 35',
        durationDays: 25,
        temperature: { min: 18, max: 32, optimalMin: 22, optimalMax: 28 },
        airHumidity: { min: 60, max: 80, optimalMin: 65, optimalMax: 75 },
        soilMoisture: { min: 55, max: 70, optimalMin: 60, optimalMax: 68 },
        light: { min: 12000, max: 45000, optimalMin: 18000, optimalMax: 35000 },
        vpd: { min: 0.8, max: 1.3, optimalMin: 0.85, optimalMax: 1.15 },
        advisoryNote: 'Vun nhẹ đất vào gốc để phần thân trắng dài và thơm ngon.',
      },
      {
        stageId: 'harvest',
        name: 'Thu hoạch nhổ tỉa',
        daysRange: 'Ngày 36 - 45',
        durationDays: 10,
        temperature: { min: 18, max: 30, optimalMin: 20, optimalMax: 26 },
        airHumidity: { min: 55, max: 75, optimalMin: 60, optimalMax: 70 },
        soilMoisture: { min: 50, max: 65, optimalMin: 55, optimalMax: 62 },
        light: { min: 10000, max: 40000, optimalMin: 15000, optimalMax: 30000 },
        vpd: { min: 0.8, max: 1.35, optimalMin: 0.9, optimalMax: 1.2 },
        advisoryNote: 'Ngưng tưới đạm trước thu hoạch 7 ngày để hạn chế thối nhũn.',
      },
    ],
  },
  {
    id: 'hung-que',
    name: 'Húng quế lá thơm',
    scientificName: 'Ocimum basilicum',
    category: 'herb',
    icon: '🌿',
    totalDays: 40,
    difficulty: 'easy',
    vietnamSeason: 'Nhiệt đới ấm áp quanh năm',
    description: 'Lá thơm cay nhẹ, chứa nhiều tinh dầu có tính kháng khuẩn và xua đuổi côn trùng.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Giâm cành & Cây con',
        daysRange: 'Ngày 1 - 8',
        durationDays: 8,
        temperature: { min: 20, max: 32, optimalMin: 24, optimalMax: 28 },
        airHumidity: { min: 70, max: 88, optimalMin: 72, optimalMax: 82 },
        soilMoisture: { min: 65, max: 80, optimalMin: 68, optimalMax: 75 },
        light: { min: 6000, max: 22000, optimalMin: 10000, optimalMax: 18000 },
        vpd: { min: 0.5, max: 0.85, optimalMin: 0.6, optimalMax: 0.78 },
        advisoryNote: 'Tránh nắng trực tiếp 3 ngày đầu đối với cành giâm.',
      },
      {
        stageId: 'vegetative',
        name: 'Phân nhánh xòe bụi',
        daysRange: 'Ngày 9 - 28',
        durationDays: 20,
        temperature: { min: 22, max: 34, optimalMin: 25, optimalMax: 30 },
        airHumidity: { min: 60, max: 80, optimalMin: 65, optimalMax: 72 },
        soilMoisture: { min: 55, max: 70, optimalMin: 60, optimalMax: 66 },
        light: { min: 15000, max: 50000, optimalMin: 22000, optimalMax: 38000 },
        vpd: { min: 0.85, max: 1.35, optimalMin: 0.95, optimalMax: 1.2 },
        advisoryNote: 'Ngắt ngọn thường xuyên để cây tạo thành bụi tròn sum suê.',
      },
      {
        stageId: 'harvest',
        name: 'Hái đọt thương phẩm',
        daysRange: 'Ngày 29 - 40',
        durationDays: 12,
        temperature: { min: 20, max: 32, optimalMin: 24, optimalMax: 28 },
        airHumidity: { min: 55, max: 75, optimalMin: 60, optimalMax: 70 },
        soilMoisture: { min: 50, max: 68, optimalMin: 55, optimalMax: 63 },
        light: { min: 12000, max: 45000, optimalMin: 18000, optimalMax: 35000 },
        vpd: { min: 0.9, max: 1.4, optimalMin: 1.0, optimalMax: 1.25 },
        advisoryNote: 'Hái nụ hoa ngay khi chớm nhú để lá không bị già và xơ.',
      },
    ],
  },
  {
    id: 'bac-ha',
    name: 'Bạc hà Peppermint / Âu',
    scientificName: 'Mentha piperita',
    category: 'herb',
    icon: '🍃',
    totalDays: 50,
    difficulty: 'easy',
    vietnamSeason: 'Quanh năm, thích ẩm mát bán râm',
    description: 'Mùi hương menthol sảng khoái, ngầm lan mạnh dưới đất, ưa ẩm nhưng sợ đọng vũng.',
    waterDemand: 'high',
    stages: [
      {
        stageId: 'seedling',
        name: 'Rễ ngầm đâm chồi',
        daysRange: 'Ngày 1 - 12',
        durationDays: 12,
        temperature: { min: 18, max: 28, optimalMin: 20, optimalMax: 25 },
        airHumidity: { min: 70, max: 90, optimalMin: 75, optimalMax: 85 },
        soilMoisture: { min: 65, max: 82, optimalMin: 70, optimalMax: 78 },
        light: { min: 5000, max: 20000, optimalMin: 8000, optimalMax: 15000 },
        vpd: { min: 0.45, max: 0.85, optimalMin: 0.55, optimalMax: 0.75 },
        advisoryNote: 'Trồng chậu riêng để rễ ngầm không xâm lấn các loại cây khác.',
      },
      {
        stageId: 'vegetative',
        name: 'Trải thảm cành lá',
        daysRange: 'Ngày 13 - 35',
        durationDays: 23,
        temperature: { min: 18, max: 30, optimalMin: 21, optimalMax: 26 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 60, max: 78, optimalMin: 65, optimalMax: 74 },
        light: { min: 10000, max: 35000, optimalMin: 15000, optimalMax: 25000 },
        vpd: { min: 0.75, max: 1.2, optimalMin: 0.85, optimalMax: 1.1 },
        advisoryNote: 'Thích hợp ánh sáng tán xạ 60-70%, tránh nắng gắt buổi trưa.',
      },
      {
        stageId: 'harvest',
        name: 'Cắt cành chiết xuất & Dùng tươi',
        daysRange: 'Ngày 36 - 50',
        durationDays: 15,
        temperature: { min: 18, max: 28, optimalMin: 20, optimalMax: 24 },
        airHumidity: { min: 60, max: 80, optimalMin: 65, optimalMax: 75 },
        soilMoisture: { min: 58, max: 72, optimalMin: 62, optimalMax: 68 },
        light: { min: 10000, max: 30000, optimalMin: 14000, optimalMax: 22000 },
        vpd: { min: 0.8, max: 1.25, optimalMin: 0.88, optimalMax: 1.15 },
        advisoryNote: 'Cắt ngang thân chừa 3-5cm, cây sẽ nhanh chóng tái sinh lứa mới.',
      },
    ],
  },
  {
    id: 'ngo-ri',
    name: 'Ngò rí (Rau mùi ta)',
    scientificName: 'Coriandrum sativum',
    category: 'herb',
    icon: '🌱',
    totalDays: 32,
    difficulty: 'easy',
    vietnamSeason: 'Vụ Thu - Đông và mùa mát',
    description: 'Hương thơm nồng dịu, rễ cọc mảnh khảnh mẫn cảm với úng và sốc nhiệt trên 30°C.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Nứt nanh & Mọc mầm',
        daysRange: 'Ngày 1 - 8',
        durationDays: 8,
        temperature: { min: 16, max: 26, optimalMin: 18, optimalMax: 23 },
        airHumidity: { min: 70, max: 88, optimalMin: 72, optimalMax: 82 },
        soilMoisture: { min: 65, max: 80, optimalMin: 68, optimalMax: 75 },
        light: { min: 4000, max: 18000, optimalMin: 6000, optimalMax: 14000 },
        vpd: { min: 0.4, max: 0.8, optimalMin: 0.5, optimalMax: 0.7 },
        advisoryNote: 'Cà nhẹ cho vỡ đôi vỏ hạt trước khi gieo để tỷ lệ mầm đạt 90%.',
      },
      {
        stageId: 'vegetative',
        name: 'Phát tán lá chân vịt',
        daysRange: 'Ngày 9 - 24',
        durationDays: 16,
        temperature: { min: 16, max: 28, optimalMin: 18, optimalMax: 24 },
        airHumidity: { min: 60, max: 80, optimalMin: 65, optimalMax: 75 },
        soilMoisture: { min: 55, max: 70, optimalMin: 60, optimalMax: 66 },
        light: { min: 8000, max: 30000, optimalMin: 12000, optimalMax: 22000 },
        vpd: { min: 0.7, max: 1.15, optimalMin: 0.8, optimalMax: 1.05 },
        advisoryNote: 'Giữ nhiệt độ mát mẻ để rau không bị vọt hoa sớm.',
      },
      {
        stageId: 'harvest',
        name: 'Nhổ cả rễ thơm',
        daysRange: 'Ngày 25 - 32',
        durationDays: 8,
        temperature: { min: 15, max: 26, optimalMin: 18, optimalMax: 22 },
        airHumidity: { min: 55, max: 75, optimalMin: 60, optimalMax: 68 },
        soilMoisture: { min: 50, max: 65, optimalMin: 55, optimalMax: 60 },
        light: { min: 8000, max: 25000, optimalMin: 10000, optimalMax: 20000 },
        vpd: { min: 0.8, max: 1.25, optimalMin: 0.85, optimalMax: 1.1 },
        advisoryNote: 'Nhổ nhẹ nhàng giữ nguyên rễ vì rễ ngò rí chứa nhiều tinh dầu thơm nhất.',
      },
    ],
  },

  // ==================== 4. HOA & CỦ QUẢ (FLOWER_ROOT) ====================
  {
    id: 'cu-cai-do',
    name: 'Củ cải đỏ tròn Cherry',
    scientificName: 'Raphanus sativus',
    category: 'flower_root',
    icon: '🥕',
    totalDays: 28,
    difficulty: 'easy',
    vietnamSeason: 'Quanh năm, đẹp nhất vụ Đông - Xuân',
    description: 'Chu kỳ siêu ngắn, củ tròn đỏ tươi giòn ngọt, trang trí ban công và chế biến salad đẹp mắt.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Mầm tơ & Bén rễ cọc',
        daysRange: 'Ngày 1 - 7',
        durationDays: 7,
        temperature: { min: 18, max: 28, optimalMin: 20, optimalMax: 25 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 65, max: 80, optimalMin: 68, optimalMax: 75 },
        light: { min: 6000, max: 22000, optimalMin: 10000, optimalMax: 18000 },
        vpd: { min: 0.5, max: 0.85, optimalMin: 0.6, optimalMax: 0.75 },
        advisoryNote: 'Tỉa định khoảng cách cây cách cây 5-7cm ngay khi có 2 lá thật.',
      },
      {
        stageId: 'tuber_expansion',
        name: 'Phình củ tròn',
        daysRange: 'Ngày 8 - 20',
        durationDays: 13,
        temperature: { min: 16, max: 27, optimalMin: 18, optimalMax: 24 },
        airHumidity: { min: 60, max: 78, optimalMin: 65, optimalMax: 72 },
        soilMoisture: { min: 60, max: 75, optimalMin: 64, optimalMax: 70 },
        light: { min: 12000, max: 40000, optimalMin: 18000, optimalMax: 30000 },
        vpd: { min: 0.75, max: 1.2, optimalMin: 0.85, optimalMax: 1.1 },
        advisoryNote: 'Đất phải tơi xốp, tưới nước đều đặn để củ không bị xơ cay và nứt nẻ.',
      },
      {
        stageId: 'harvest',
        name: 'Củ đẫy đà & Thu hoạch',
        daysRange: 'Ngày 21 - 28',
        durationDays: 8,
        temperature: { min: 16, max: 26, optimalMin: 18, optimalMax: 23 },
        airHumidity: { min: 55, max: 75, optimalMin: 60, optimalMax: 68 },
        soilMoisture: { min: 55, max: 68, optimalMin: 58, optimalMax: 64 },
        light: { min: 10000, max: 35000, optimalMin: 15000, optimalMax: 26000 },
        vpd: { min: 0.8, max: 1.25, optimalMin: 0.88, optimalMax: 1.15 },
        advisoryNote: 'Nhổ khi đường kính củ đạt 2.5 - 3.5cm, để quá ngày củ sẽ bị xốp rỗng ruột.',
      },
    ],
  },
  {
    id: 'ca-rot-mini',
    name: 'Cà rốt mini Chantenay',
    scientificName: 'Daucus carota subsp. sativus',
    category: 'flower_root',
    icon: '🥕',
    totalDays: 65,
    difficulty: 'medium',
    vietnamSeason: 'Thu - Đông (tháng 9 đến tháng 2 năm sau)',
    description: 'Củ ngọt đậm, giàu beta-carotene, thích hợp đất pha cát tơi xốp sâu 25cm.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'seedling',
        name: 'Mầm tơ & Rễ cọc đâm sâu',
        daysRange: 'Ngày 1 - 15',
        durationDays: 15,
        temperature: { min: 16, max: 26, optimalMin: 18, optimalMax: 23 },
        airHumidity: { min: 70, max: 88, optimalMin: 72, optimalMax: 82 },
        soilMoisture: { min: 65, max: 80, optimalMin: 70, optimalMax: 76 },
        light: { min: 6000, max: 20000, optimalMin: 10000, optimalMax: 16000 },
        vpd: { min: 0.45, max: 0.85, optimalMin: 0.55, optimalMax: 0.75 },
        advisoryNote: 'Đất không được có sỏi đá vụn làm củ bị chẻ đôi biến dạng.',
      },
      {
        stageId: 'root_growth',
        name: 'Phát triển chiều dài củ',
        daysRange: 'Ngày 16 - 45',
        durationDays: 30,
        temperature: { min: 16, max: 27, optimalMin: 19, optimalMax: 24 },
        airHumidity: { min: 60, max: 78, optimalMin: 65, optimalMax: 72 },
        soilMoisture: { min: 60, max: 75, optimalMin: 64, optimalMax: 70 },
        light: { min: 12000, max: 45000, optimalMin: 20000, optimalMax: 35000 },
        vpd: { min: 0.8, max: 1.25, optimalMin: 0.85, optimalMax: 1.1 },
        advisoryNote: 'Bón bổ sung kali để củ phình to và tích lũy sắc tố cam đậm.',
      },
      {
        stageId: 'harvest',
        name: 'Chắc củ & Thu hoạch',
        daysRange: 'Ngày 46 - 65',
        durationDays: 20,
        temperature: { min: 15, max: 25, optimalMin: 18, optimalMax: 22 },
        airHumidity: { min: 55, max: 72, optimalMin: 60, optimalMax: 66 },
        soilMoisture: { min: 50, max: 65, optimalMin: 55, optimalMax: 60 },
        light: { min: 10000, max: 40000, optimalMin: 16000, optimalMax: 30000 },
        vpd: { min: 0.85, max: 1.35, optimalMin: 0.9, optimalMax: 1.2 },
        advisoryNote: 'Tưới ẩm đất nhẹ trước khi nhổ 2 giờ để nhổ củ trơn tru không bị đứt rễ.',
      },
    ],
  },
  {
    id: 'hoa-lan-ho-diep',
    name: 'Hoa Lan Hồ Điệp công nghệ cao',
    scientificName: 'Phalaenopsis',
    category: 'flower_root',
    icon: '🌸',
    totalDays: 120,
    difficulty: 'hard',
    vietnamSeason: 'Quanh năm trong nhà màng kiểm soát khí hậu',
    description: 'Nữ hoàng hoa cảnh, rễ khí sinh ưa ẩm nhưng cực sợ úng, nhiệt độ chênh lệch ngày đêm kích nụ.',
    waterDemand: 'low',
    stages: [
      {
        stageId: 'vegetative',
        name: 'Dưỡng lá & Rễ gió',
        daysRange: 'Ngày 1 - 45',
        durationDays: 45,
        temperature: { min: 22, max: 30, optimalMin: 24, optimalMax: 28 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 45, max: 65, optimalMin: 50, optimalMax: 60 },
        light: { min: 8000, max: 22000, optimalMin: 12000, optimalMax: 18000 },
        vpd: { min: 0.6, max: 1.0, optimalMin: 0.7, optimalMax: 0.9 },
        advisoryNote: 'Dùng vỏ thông và than hoạt tính, chỉ tưới khi giá thể se khô mặt.',
      },
      {
        stageId: 'spike_induction',
        name: 'Xử lý sốc lạnh kích vòi hoa',
        daysRange: 'Ngày 46 - 75',
        durationDays: 30,
        temperature: { min: 16, max: 24, optimalMin: 18, optimalMax: 22 },
        airHumidity: { min: 60, max: 75, optimalMin: 65, optimalMax: 70 },
        soilMoisture: { min: 40, max: 60, optimalMin: 45, optimalMax: 55 },
        light: { min: 10000, max: 26000, optimalMin: 14000, optimalMax: 20000 },
        vpd: { min: 0.7, max: 1.2, optimalMin: 0.8, optimalMax: 1.05 },
        advisoryNote: 'Chênh lệch nhiệt độ ngày 24°C và đêm 18°C trong 4 tuần kích ngồng hoa vươn dài.',
      },
      {
        stageId: 'blooming',
        name: 'Nở hoa & Trưng hoa bền màu',
        daysRange: 'Ngày 76 - 120',
        durationDays: 45,
        temperature: { min: 18, max: 26, optimalMin: 20, optimalMax: 24 },
        airHumidity: { min: 55, max: 70, optimalMin: 60, optimalMax: 68 },
        soilMoisture: { min: 40, max: 55, optimalMin: 45, optimalMax: 50 },
        light: { min: 8000, max: 20000, optimalMin: 10000, optimalMax: 16000 },
        vpd: { min: 0.75, max: 1.25, optimalMin: 0.85, optimalMax: 1.1 },
        advisoryNote: 'Tuyệt đối không phun sương trực tiếp lên cánh hoa để hoa bền 2-3 tháng.',
      },
    ],
  },
  {
    id: 'hoa-hong-mon',
    name: 'Hoa Hồng Môn kiểng',
    scientificName: 'Anthurium andraeanum',
    category: 'flower_root',
    icon: '🌺',
    totalDays: 90,
    difficulty: 'medium',
    vietnamSeason: 'Quanh năm, thích bóng râm mát',
    description: 'Lá hình tim xanh bóng, hoa cờ đỏ tươi sang trọng, lọc không khí và khí độc trong nhà rất tốt.',
    waterDemand: 'medium',
    stages: [
      {
        stageId: 'vegetative',
        name: 'Dưỡng bẹ lá xanh mướt',
        daysRange: 'Ngày 1 - 40',
        durationDays: 40,
        temperature: { min: 18, max: 30, optimalMin: 22, optimalMax: 27 },
        airHumidity: { min: 65, max: 85, optimalMin: 70, optimalMax: 80 },
        soilMoisture: { min: 55, max: 70, optimalMin: 60, optimalMax: 66 },
        light: { min: 5000, max: 18000, optimalMin: 8000, optimalMax: 14000 },
        vpd: { min: 0.6, max: 1.0, optimalMin: 0.7, optimalMax: 0.9 },
        advisoryNote: 'Tránh nắng trực tiếp 100% để phiến lá không bị cháy xém.',
      },
      {
        stageId: 'flowering',
        name: 'Trổ mo hoa đỏ & Khoe sắc',
        daysRange: 'Ngày 41 - 90',
        durationDays: 50,
        temperature: { min: 18, max: 28, optimalMin: 20, optimalMax: 25 },
        airHumidity: { min: 60, max: 80, optimalMin: 65, optimalMax: 75 },
        soilMoisture: { min: 50, max: 68, optimalMin: 55, optimalMax: 62 },
        light: { min: 6000, max: 20000, optimalMin: 10000, optimalMax: 16000 },
        vpd: { min: 0.7, max: 1.2, optimalMin: 0.8, optimalMax: 1.05 },
        advisoryNote: 'Tưới vào sáng sớm, lau bụi trên lá định kỳ để cây quang hợp tối đa.',
      },
    ],
  },
];
